apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: healthcare-{{ .Values.global.environment }}
  labels:
    app: appointment-service
    environment: {{ .Values.global.environment }}
spec:
  type: {{ .Values.appointmentService.service.type }}
  ports:
  - port: {{ .Values.appointmentService.service.port }}
    targetPort: 3001
    protocol: TCP
  selector:
    app: appointment-service