apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: {{ .Values.global.namespace }}
data:
  ENVIRONMENT: "{{ .Values.global.environment }}"
  IMAGE_REGISTRY: "{{ .Values.global.imageRegistry }}"