{{- $namespace := .Values.global.namespace }}

{{- range $svc := list .Values.patientService .Values.appointmentService }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc.name }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $svc.name }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app: {{ $svc.name }}
  template:
    metadata:
      labels:
        app: {{ $svc.name }}
    spec:
      {{- if $.Values.global.useImagePullSecrets }}
      imagePullSecrets:
        - name: {{ $.Values.global.acrSecretName }}
      {{- end }}
      containers:
        - name: {{ $svc.name }}
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $svc.containerPort }}
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: global-config
{{- end }}
