{{- $namespace := .Values.global.namespace }}

{{- range $svc := list .Values.patientService .Values.appointmentService }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  namespace: {{ $namespace }}
spec:
  selector:
    app: {{ $svc.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ $svc.containerPort }}
  type: ClusterIP
{{- end }}
