apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: healthcare-{{ .Values.global.environment }}
  labels:
    app: patient-service
    environment: {{ .Values.global.environment }}
spec:
  type: {{ .Values.patientService.service.type }}
  ports:
  - port: {{ .Values.patientService.service.port }}
    targetPort: 3000
    protocol: TCP
  selector:
    app: patient-service