apiVersion: v2
name: healthcare-microservices
description: Healthcare microservices deployment (patient + appointment)
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: ingress-nginx
    version: 4.11.2
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
