apiVersion: v2
name: healthcare-microservices
description: A Helm chart for Kubernetes deployment of healthcare microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress-nginx.enabled